version: '3'

services:
  tezaurs:
    image: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "${DB_SERVICE_BIND_IP:-127.0.0.1}:$DB_SERVICE_PORT:$DB_SERVICE_PORT"
    volumes:
      - ${LOCAL_DUMP_DIR}:/dumps
      - ${DATA_DIR:-pdb-data}:/var/lib/postgresql/data
      - ./docker.initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    command: 'postgres
                -p $DB_SERVICE_PORT
                -c default_statistics_target=500
                -c jit=off
                -c work_mem=40MB
                -c temp_buffers=20MB
                -c max_wal_size=4GB
                -c idle_in_transaction_session_timeout=1800000
                '   